# Generated by Django 2.2.4 on 2021-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'upcoming'), (2, 'incipient'), (3, 'completed'), (4, 'cancelled')], default=1),
        ),
    ]
